import { AiBadge } from '@/components/primitives/AiBadge';
import { SectionBar } from '@/components/primitives/SectionBar';

/**
 * Editorial daily-recap section. Currently renders a hand-written
 * placeholder marked as preview content; Phase 9F swaps the body to
 * Claude-generated paragraphs from `useDailyContent`.
 */

const PLACEHOLDER_PARAGRAPHS: readonly string[] = [
  "Across the league, the early-season patterns are starting to harden — division leaders separating from the pack, bullpens getting taxed in the run-up to the first off-day, and a handful of pitchers reshaping their profiles in real time. The rotations that looked stretched in March are settling; the lineups that looked thin are finding their second wave.",
  "Tonight's slate brings the kind of matchups that swing both standings and storylines. Watch the early innings closely — bullpen usage from the last week of high-leverage games will tell you which clubs have a margin tonight and which are flying without a net.",
];

const TODAY_KICKER = (() => {
  const d = new Date();
  return d
    .toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })
    .toUpperCase();
})();

export function DailyRecapSection() {
  return (
    <section className="rounded-l border border-hairline-strong bg-white px-9 py-8 shadow-sm">
      <SectionBar
        title="Around the League · Today"
        subtitle="Daily MLB recap, generated by Claude"
        right={<AiBadge />}
      />

      <div className="text-[11px] font-semibold uppercase tracking-[0.06em] text-paper-4">
        {TODAY_KICKER}
      </div>

      <div
        className="mt-3 flex flex-col gap-4 text-paper-2"
        style={{ maxWidth: '70ch', fontSize: 15, lineHeight: 1.65 }}
      >
        {PLACEHOLDER_PARAGRAPHS.map((p, i) => (
          <p key={i} className="m-0 italic">
            {p}
          </p>
        ))}
      </div>

      <div className="mt-6 border-t border-hairline pt-3 text-[11px] italic text-paper-4">
        Sample preview — the daily recap will be generated by Claude Sonnet 4.6
        from the previous day's final game data and the day's slate.
      </div>
    </section>
  );
}
