import { AiBadge } from '@/components/primitives/AiBadge';
import { SectionBar } from '@/components/primitives/SectionBar';
import { TeamChip } from '@/components/primitives/TeamChip';
import { Skeleton } from '@/components/primitives/Skeleton';
import type { AppContentItem, AppGame } from '@/types/app';

/**
 * Yesterday's Game Recaps — stacked vertical list, one card per recap.
 * Each card shows the matchup, the final score, and the AI-generated
 * paragraphs split on blank lines.
 *
 * State machine:
 *   isLoading  → 3 skeleton cards
 *   isError    → placeholder paragraphs, "API unavailable" footer
 *   isEmpty    → placeholder paragraphs, "Sample preview" footer
 *   has data   → real recap cards rendered top-to-bottom
 */

interface DailyRecapSectionProps {
  recap: readonly AppContentItem[];
  isLoading: boolean;
  isError: boolean;
  isEmpty: boolean;
  /** Resolves an AI item's gamePk to the matching scoreboard game. */
  gamesByPk: ReadonlyMap<number, AppGame>;
}

const PLACEHOLDER_PARAGRAPHS: readonly string[] = [
  "Across the league, the early-season patterns are starting to harden — division leaders separating from the pack, bullpens getting taxed in the run-up to the first off-day, and a handful of pitchers reshaping their profiles in real time. The rotations that looked stretched in March are settling; the lineups that looked thin are finding their second wave.",
  "Tonight's slate brings the kind of matchups that swing both standings and storylines. Watch the early innings closely — bullpen usage from the last week of high-leverage games will tell you which clubs have a margin tonight and which are flying without a net.",
];

export function DailyRecapSection({
  recap,
  isLoading,
  isError,
  isEmpty,
  gamesByPk,
}: DailyRecapSectionProps) {
  return (
    <section className="rounded-l border border-hairline-strong bg-white px-9 py-8 shadow-sm">
      <SectionBar
        title="Yesterday's Game Recaps"
        subtitle="One short editorial per Final game, generated by Claude"
        right={<AiBadge />}
      />

      {isLoading ? (
        <RecapSkeleton />
      ) : isError ? (
        <PlaceholderProse footer="API unavailable — showing sample copy." />
      ) : isEmpty || recap.length === 0 ? (
        <PlaceholderProse footer="Sample preview — recaps will be generated by Claude Sonnet 4.6 from each game's final state." />
      ) : (
        <div className="mt-3 flex flex-col gap-5">
          {recap.map((item) => (
            <RecapCard
              key={item.gamePk}
              item={item}
              game={gamesByPk.get(item.gamePk)}
            />
          ))}
        </div>
      )}
    </section>
  );
}

function RecapCard({ item, game }: { item: AppContentItem; game: AppGame | undefined }) {
  if (!game) {
    // Graceful degradation — AI text without a matchup headline. Should be
    // rare; would only happen if the backend has a recap for a gamePk that
    // dropped off both date partitions of today's scoreboard fetch.
    if (typeof console !== 'undefined') {
      console.warn(`Recap for gamePk ${item.gamePk} has no matching game in scoreboard`);
    }
  }

  const paragraphs = item.text.split(/\n\s*\n/).filter((p) => p.trim().length > 0);

  return (
    <article className="rounded-l border border-hairline bg-surface-1 p-5">
      {game ? (
        <div className="mb-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <TeamSide
              abbr={game.away.abbreviation}
              color={game.away.primaryColor}
              logoPath={game.away.logoPath}
              name={game.away.fullName}
              score={game.awayScore}
              winner={game.awayScore > game.homeScore}
            />
            <span className="text-[11px] font-semibold uppercase tracking-[0.08em] text-paper-5">
              at
            </span>
            <TeamSide
              abbr={game.home.abbreviation}
              color={game.home.primaryColor}
              logoPath={game.home.logoPath}
              name={game.home.fullName}
              score={game.homeScore}
              winner={game.homeScore > game.awayScore}
            />
          </div>
        </div>
      ) : (
        <div className="mb-3 text-[11px] font-semibold uppercase tracking-[0.08em] text-paper-4">
          Game pk {item.gamePk}
        </div>
      )}

      <div
        className="flex flex-col gap-3 text-paper-2"
        style={{ maxWidth: '70ch', fontSize: 14.5, lineHeight: 1.65 }}
      >
        {paragraphs.map((p, i) => (
          <p key={i} className="m-0">
            {p}
          </p>
        ))}
      </div>
    </article>
  );
}

interface TeamSideProps {
  abbr: string;
  color: string;
  logoPath: string;
  name: string;
  score: number;
  winner: boolean;
}

function TeamSide({ abbr, color, logoPath, name, score, winner }: TeamSideProps) {
  return (
    <div className="flex items-center gap-2">
      <TeamChip abbr={abbr} color={color} logoPath={logoPath} size={28} />
      <div className="flex flex-col leading-tight">
        <span
          className={[
            'text-[13px] -tracking-[0.01em]',
            winner ? 'font-bold text-paper' : 'text-paper-3',
          ].join(' ')}
        >
          {name}
        </span>
        <span className={['mono text-[12px]', winner ? 'text-paper' : 'text-paper-4'].join(' ')}>
          {score}
        </span>
      </div>
    </div>
  );
}

function PlaceholderProse({ footer }: { footer: string }) {
  return (
    <>
      <div
        className="mt-3 flex flex-col gap-4 text-paper-2"
        style={{ maxWidth: '70ch', fontSize: 15, lineHeight: 1.65 }}
      >
        {PLACEHOLDER_PARAGRAPHS.map((p, i) => (
          <p key={i} className="m-0 italic">
            {p}
          </p>
        ))}
      </div>
      <div className="mt-6 border-t border-hairline pt-3 text-[11px] italic text-paper-4">
        {footer}
      </div>
    </>
  );
}

function RecapSkeleton() {
  return (
    <div className="mt-3 flex flex-col gap-5" data-testid="recap-skeleton">
      {[0, 1, 2].map((i) => (
        <div key={i} className="rounded-l border border-hairline bg-surface-1 p-5">
          <Skeleton className="mb-3 h-6 w-1/2" />
          <Skeleton className="mb-2 h-4 w-full" />
          <Skeleton className="mb-2 h-4 w-11/12" />
          <Skeleton className="h-4 w-9/12" />
        </div>
      ))}
    </div>
  );
}
